version: '3'
services:
  django:
    build: ./simple_project/app
    container_name: django_app
    env_file:
      - ./simple_project/app/.env
    volumes:
      - ./simple_project/app/static:/var/www/static
      - ./simple_project/app:/opt/app
    depends_on:
      - theatre-db
    expose: 
      - 8000
    networks:
      - movie_network

# к сожалению не получилось пробросить сюда переменные из .env ни в какую не пробрасывались
  theatre-db:
    image: postgres:16
    environment: 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: theatre-dbn
    env_file:
      - ./simple_project/app/.env
    volumes:
      - ./simple_project/theatre-db/init/:/docker-entrypoint-initdb.d
      - $HOME/postgresql/theatre-db_data:/var/lib/postgresql/theatre-db_data    
    networks:
      - movie_network


  nginx:
      image: nginx:latest
      volumes:
        - ./simple_project/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./simple_project/configs:/etc/nginx/conf.d:ro
        - ./simple_project/app/static:/var/www/static
      container_name: nginx
      depends_on:
        - theatre-db
      networks:
        - movie_network

  swagger-ui:
      image: swaggerapi/swagger-ui 
      container_name: swagger
      volumes:
        - ./simple_project/swagger/openapi.yaml:/swagger.yaml
      environment:
        SWAGGER_JSON: /swagger.yaml 
      networks:
        - movie_network


networks:
  movie_network:
    driver: bridge